server:
  port: 8080

spring:
  application:
    name: e-budget

eureka:
  client:
    enabled: false

cassandra:
  contact-points: 10.0.10.104,10.0.10.105,10.0.10.106
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: brT4Kn27RQs


ocds.prefix: t1s2t3