server:
  port: 8080

spring:
  application:
    name: e-budget

eureka:
  client:
    enabled: false

cassandra:
  contact-points: dev.ac-node1.eprocurement.systems,dev.ac-node2.eprocurement.systems,dev.ac-node3.eprocurement.systems
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: 6AH7vbrkMWnfK

ocds.prefix: t1s2t3