server:
  port: 8080

spring:
  application:
    name: e-budget

cassandra:
  contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: 6AH7vbrkMWnfK

ocds:
  prefixes:
    main: ocds-t1s2t3
    test: test-t1s2t3