server:
  port: 8080

spring:
  application:
    name: e-budget

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042

ocds:
  prefixes:
    main: ocds-t1s2t3
    test: test-t1s2t3