server:
  port: 8080

spring:
  application:
    name: e-budget

eureka:
  client:
    enabled: false

cassandra:
  contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: brT4Kn27RQs

ocds.prefix: t1s2t3