package com.procurement.budget.exception

enum class ErrorType constructor(val code: String, val message: String) {
    INVALID_JSON_TYPE("00.00", "Invalid json type"),
    EI_NOT_FOUND("00.01", "EI not found."),
    FS_NOT_FOUND("00.02", "FS not found."),
    INVALID_OWNER("00.03", "Invalid owner."),
    INVALID_TOKEN("00.04", "Invalid token."),
    INVALID_CPV("00.05", "Invalid CPV."),
    INVALID_CURRENCY("00.06", "Invalid currency."),
    INVALID_AMOUNT("00.07", "Invalid amount."),
    INVALID_STATUS("00.08", "Financial source status invalid."),
    INVALID_SOURCE_ENTITY("00.09", "FS source entity invalid."),
    INVALID_BUDGET_ID("00.10", "Budget id must not be empty."),
    INVALID_BUYER_ID("00.11", "Invalid Buyer id."),
    INVALID_OCID_ID("00.11", "OCID of FS must not be empty."),
    INVALID_VERIFIED("00.11", "Verified of FS must not be empty."),
    INVALID_MPC("00.12", "Invalid main procurement category."),
    INVALID_OCID("00.13", "Invalid ocid."),
    INVALID_BUDGET_BREAKDOWN_ID("00.14", "Invalid budget breakdown id "),
    INVALID_PERIOD("01.01", "Invalid period."),
    INVALID_DATE("01.02", "Date does not match the period."),
    PARAM_ERROR("01.03", "Should not be empty for this type of operation"),
    INVALID_EUROPEAN("01.04", "EuropeanUnionFunding must not be empty."),
    INVALID_TENDER_ID("01.05", "Invalid tender id."),
    INVALID_BA_PERIOD("01.06", "Invalid budget allocation period."),
    INVALID_BA_ID("01.07", "Invalid budget allocation id."),
    PERSONES("01.08", "Invalid persones"),
    PERSON_NOT_FOUND("01.09", "Person not found."),
    BF("01.10", "Invalid business functions of person."),
    INVALID_BA("01.11", "Budget allocations are not complete."),
    DOCUMENTS("01.1", "Documents is not valid"),
    RULES_NOT_FOUND("02.01", "Rules not found."),
    CONTEXT("20.02", "Context parameter not found."),
    PERSONES_IN_BUYER_IS_EMPTY_OR_MISSING("20.03", "The list of the persones in the buyer is empty or missing."),
    BUSINESS_FUNCTIONS_IN_PERSON_IN_BUYER_IS_EMPTY_OR_MISSING("20.04", "The list of the business functions in the person is empty or missing."),
    DOCUMENTS_BUSINESS_FUNCTION_IN_PERSON_IN_BUYER_IS_EMPTY_OR_MISSING("20.05", "The list of the documents in the business function is empty or missing."),
    BANK_ACCOUNTS_IN_DETAILS_IN_BUYER_IS_EMPTY_OR_MISSING("20.06", "The list of the bank accounts in the details of the buyer is empty or missing."),
    ADDITIONAL_IDENTIFIERS_IN_BUYER_IS_EMPTY_OR_MISSING("20.07", "The list of the additional identifiers in the buyer is empty or missing."),
    INVALID_BUSINESS_FUNCTION_TYPE("20.08", "A person with a business function type 'authority' should be used for the confirmation request."),
    INVALID_ITEM_QUANTITY("20.09", "Invalid item quantity."),
    DUPLICATED_ITEMS("20.10", "Duplicated items found."),
    INCORRECT_VALUE_ATTRIBUTE("20.11", "Incorrect an attribute value.");
}
